### ISSUE TITLE
Multiple EGM Model required

### ISSUE THREAD

**Issue by ttramontinwing** [porosnie/ED-xxx#11]
(Open Consultation #106) add dedicated field in DatasetMetadata,otherGeoid as string defined by the EPSG URI to support multiple EGM Models

**Comment by porosnie** [comment]
I propose to use the URN format for this field, for compatibility with AIXM. This means:
- in the UML data model there is a new data type "URNType" defined as "A string of characters that complies with the Uniform Resource Name (URN) scheme as specified in the RFC 2141."
- EGM2008 would then be coded with the following: "urn:ogc:def:crs:EPSG::3855". This is aligned with the OpenGeospatial convention for coordinate reference systems, which is also used in AIXM: https://ext.eurocontrol.int/aixm_confluence/display/public/ACG/Coordinate+Reference+System

**Comment by porosnie** [comment]
Done in the UML model, to be done in the JSON schema

**Comment by porosnie** [comment]
Added URNtype in data type schema. Remains to add the otherGeoid property. Also, maybe the URNType can be further constrained, to only allow URI patterns?

**Comment by porosnie** [comment]
Added otherGeoid in metadata

**Comment by porosnie** [comment]
I think that for this edition it is too early to constrain the URNType for URI patterns only.
