### ISSUE TITLE
unsupported type for "upper" and "lower"

### ISSUE THREAD

**Issue by ttramontinwing** [porosnie/ED-xxx#13]
(open consultation #56) upper and lower are declared as double, JSON doesn't support double so the schema should be updated to reference "number"

**Comment by porosnie** [comment]
This also affects the radius property in the HorizontalExtent.

**Comment by porosnie** [comment]
Changed "double" to "number" in the UML model

**Comment by porosnie** [comment]
It was already correct ("number") in the Json Schema.

**Comment by porosnie** [comment]
It was already correct ("number") in the Json Schema.
