### ISSUE TITLE
Add TextLongType to schema

### ISSUE THREAD

**Issue by ttramontinwing** [porosnie/ED-xxx#16]
(open consultation #65) add "TextLongType" as a new possibility, similar to TextShortType, but limited to 1000 chararceters instead of 200 characters

**Comment by porosnie** [comment]
According to the Word version received from Stephane, the new TextLongType is used only for the UASZone.message, This was not specified in the Excel file. I have updated the UML model accordingly.

**Comment by porosnie** [comment]
done in data types schema
