### ISSUE TITLE
UAS Geozone Metadata fields should be optional

### ISSUE THREAD

**Issue by ttramontinwing** [porosnie/ED-xxx#18]
(open consultation #29) Amend the schema to have all metadata fields for UAS Geozone as optional

**Comment by porosnie** [comment]
This is in contradiction with #15, which says that " provider" should be required.

I think that we should give priority to this issue (#18) and overrule issue #15, which was only a comment on the discrepancy between the UML model and JSON schema.

**Comment by porosnie** [comment]
removed required properties from metadata
