### ISSUE TITLE
Missing UASZone.dataSource

### ISSUE THREAD

**Issue by BenjaminPelletier** [porosnie/ED-xxx#3]
`USpace Zone::UASZone`'s optional member `dataSource` of type `USpaceZone::Metadata` from the current standard text is not defined in this repository.  (members: `creationDateTime`, `updateDateTime`, `author`)

**Comment by porosnie** [comment]
This is not expected to be included in the GeoZone files. It is only part of the UML model and it is expected to be used only on the data provider side (State) for traceability purpose. It does not need to be added to the GeoJSON schema.

**Comment by porosnie** [comment]
No change is necessary
